### PR TITLE
Add Microsoft Kinect v2 sensor driver

### PR DESCRIPTION
**Pull request by mvm9289**
This pull requests includes different commits which add Microsoft Kinect v2 support in OpenNI 2. It implements a new OpenNI 2 driver based on the official Microsoft SDK.

Videomodes supported by this driver:
- Color: RGB888          1920x1080 30fps
- Color: RGB888          960x540   30fps
- Depth: DepthPixel      512x424   30fps
- IR:    Gray16 (ushort) 512x424   30fps

Features supported by this driver:
- DEPTH_TO_COLOR_REGISTRATION

### CODE REVIEW

**Comment by ani-rudh** [comment]
Hello guys,

maybe a little too late to ask this, but I really need help:
I am trying to build the OpenNI2.sln with visual studio 2013 (x64) on windows 10. I am getting the following errors:

Error	1	error C1083: Cannot open include file: 'NuiApi.h': No such file or directory	f:\edu_software\openni2-kinect2\openni2-kinect2\source\drivers\kinect\BaseKinectStream.h	27	1	Kinect
Error	2	error C1083: Cannot open include file: 'NuiApi.h': No such file or directory	f:\edu_software\openni2-kinect2\openni2-kinect2\source\drivers\kinect\BaseKinectStream.h	27	1	Kinect
Error	3	error C1083: Cannot open include file: 'NuiApi.h': No such file or directory	f:\edu_software\openni2-kinect2\openni2-kinect2\source\drivers\kinect\BaseKinectStream.h	27	1	Kinect
Error	4	error C1083: Cannot open include file: 'NuiApi.h': No such file or directory	f:\edu_software\openni2-kinect2\openni2-kinect2\source\drivers\kinect\BaseKinectStream.h	27	1	Kinect
Error	6	error C1083: Cannot open include file: 'NuiApi.h': No such file or directory	f:\edu_software\openni2-kinect2\openni2-kinect2\source\drivers\kinect\KinectDriver.h	27	1	Kinect
Error	7	error C1083: Cannot open include file: 'NuiApi.h': No such file or directory	f:\edu_software\openni2-kinect2\openni2-kinect2\source\drivers\kinect\BaseKinectStream.h	27	1	Kinect
Error	8	error C1083: Cannot open include file: 'NuiApi.h': No such file or directory	f:\edu_software\openni2-kinect2\openni2-kinect2\source\drivers\kinect\BaseKinectStream.h	27	1	Kinect
Warning	5	warning RC4011: identifier truncated to '_CRT_USE_WINAPI_FAMILY_DESKTOP_'	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\malloc.h	168	1	OpenNI
openni


Is there something i am doing wrong, could you please guide me .
Also, Does the OpenNI2.2.0.33 hosted on the structure.io website come with the Kinect v2.0 functionality?

**Comment by harry19902002** [comment]
I have the same question with @ani-rudh . How can I solve it?

**Comment by ani-rudh** [comment]
@harry19902002 : unload the "kinect" project under drivers. It's for kinect version 1. If you do not have the kinect 1.x sdk, then this error is encountered

**Comment by ani-rudh** [comment]
@harry19902002 : unload the "kinect" project under drivers. It's for kinect version 1. If you do not have the kinect 1.x sdk, then this error is encountered

**Comment by harry19902002** [comment]
@ani-rudh Thanks you very much.I can compile the project. But it still explains "no device found". I have not found the reason.

**Comment by ani-rudh** [comment]
Copy the kinect2.dll file to same directory as the simpleviewer.exe, it
works for me.

**Pull request closed without merging**
